export const CHECKLIST_LABELS: Record<string, string> = {
    "epi_capacete": "Capacete com jugular",
    "epi_oculos": "Óculos de proteção ou viseira",
    "epi_auricular": "Protetor auricular",
    "epi_luvas": "Luvas de segurança",
    "epi_botina": "Botina/bota de segurança antiderrapante",
    "epi_calca": "Calça de proteção para uso de motosserra",
    "epi_colete": "Colete refletivo (quando em via pública)",
    "eq_motosserra": "Motosserra em boas condições de uso",
    "eq_freio": "Freio de corrente funcionando",
    "eq_tensao": "Corrente corretamente tensionada e afiada",
    "eq_abastecimento": "Abastecimento adequado (combustível e óleo da corrente)",
    "sin_isolamento": "Área devidamente isolada",
    "sin_cones": "Uso de cones, fitas ou barreiras",
    "sin_pedestres": "Controle de acesso de pedestres e veículos",
    "sin_vigia": "Vigia/apoio em solo designado (quando necessário)",
    "alt_capacitado": "Trabalhador capacitado para trabalho em altura",
    "alt_cinto": "Cinto tipo paraquedista",
    "alt_talabarte": "Talabarte com absorvedor de energia",
    "alt_ancoragem": "Pontos de ancoragem verificados",
    "alt_escada": "Escada ou sistema de acesso em boas condições",
    "op_comunicacao": "Comunicação definida entre equipe",
    "op_fuga": "Rota de fuga definida",
    "op_primeiros": "Kit de primeiros socorros disponível",
    "op_clima": "Condições climáticas favoráveis",
    "ent_eletrica": "Presença de rede elétrica próxima",
    "ent_edificacoes": "Proximidade de edificações",
    "ent_vias": "Proximidade de vias públicas",
    "ent_interdicao": "Necessidade de interdição",
    "apoio_cordas": "Uso de cordas para descida controlada",
    "apoio_cintas": "Uso de cintas, roldanas ou mosquetões",
    "apoio_mecanizado": "Equipamento mecanizado de apoio"
};
